version: "2"
services:
  web:
    restart: always
    build: .
    container_name: kodikosERP
    ports:
      - "35729:35729"
      - "4200:4200"
      - "4500:4500"
      - "4501:4501"
      - "4502:4502"
      - "5500:5500"
      - "5501:5501"
      - "5502:5502"
    environment:
      - NODE_ENV=development
    volumes_from:
      - web-data
  web-data:
    build: .
    entrypoint: /bin/true
    volumes:
      - ./:/opt/mean.js
      - /opt/mean.js/node_modules
      - /opt/mean.js/public
      - /opt/mean.js/uploads
