export interface User {
  id?: string;
  _id?: string;
  accountManager?: string;
  accountManagerLogin?: string;
  addBy?: { login?: string, name?: string, surname?: string, email?: string };
  modBy?: { login?: string, name?: string, surname?: string, email?: string };
  addDate?: Date;
  modDate?: Date;
  login?: string;
  // username i displayName używane do logowanie do active directory
  username?: string;
  password?: string;
  name?: string;
  drugieImie?: string;
  surname?: string;
  displayName?: string;
  plec?: string;
  email?: string;
  phone?: string;
  department?: string;
  pliki?: any;
  uwagi?: string;
  aktualnePracujacy?: boolean;
  status?: string;
  moduly?: string[];
  contractorFields?: {
    accountManager?: boolean,
    accountManagerLogin?: boolean,
    addBy?: boolean,
    addDate?: boolean,
    balance?: boolean,
    ceo?: boolean,
    city?: boolean,
    comments?: boolean,
    contrType?: boolean,
    country?: boolean,
    creditLimit?: boolean,
    creditLimitCurrency?: boolean,
    fullName?: boolean,
    krs?: boolean,
    modBy?: boolean,
    modDate?: boolean,
    nip?: boolean,
    paymentDeadline?: boolean,
    postcode?: boolean,
    regon?: boolean,
    shortName?: boolean,
    status?: boolean,
    street?: boolean,
    countryShipping?: boolean,
    streetShipping?: boolean,
    cityShipping?: boolean,
    postcodeShipping?: boolean,
    buttonDodajKontr?: boolean,
    buttonOfertaKontr?: boolean,
    buttonEdytujKontr?: boolean,
    buttonUsunKontr?: boolean,
    widziWszystkie?: boolean
  };
  szkodliwaFields?: {
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  assortmentFields?: {
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  przesylkiFields?: {
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  warehouseFields?: {
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  sekretariatFields?: {
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  kluczeFields?: {
    menuKluczeUprawnienia?: boolean;
    menuDodajUprawnienia?: boolean;
    dodajUprSaAktywne?: boolean;
    menuSpis?: boolean;
    menuDodajSpis?: boolean;
    menuWydania?: boolean;
    menuDodajWydanie?: boolean;
    rejestracja?: boolean;
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  kluczeRejestrFields?: {
    menuKluczeUprawnienia?: boolean;
    menuDodajUprawnienia?: boolean;
    dodajUprSaAktywne?: boolean;
    menuSpis?: boolean;
    menuDodajSpis?: boolean;
    menuWydania?: boolean;
    menuDodajWydanie?: boolean;
    rejestracja?: boolean;
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  kluczeWydaniaFields?: {
    menuKluczeUprawnienia?: boolean;
    menuDodajUprawnienia?: boolean;
    dodajUprSaAktywne?: boolean;
    menuSpis?: boolean;
    menuDodajSpis?: boolean;
    menuWydania?: boolean;
    menuDodajWydanie?: boolean;
    rejestracja?: boolean;
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
  kluczeRejestratorFields?: {
    comments?: boolean;
    status?: boolean;
    buttonDodajKontr?: boolean;
    buttonOfertaKontr?: boolean;
    buttonEdytujKontr?: boolean;
    buttonUsunKontr?: boolean;
    projekty?: boolean;
    firmy?: boolean;
    widziWszystkie?: boolean;
    pliki?: boolean;
    buttonPliki?: boolean;
  };
}
